spring.application.name=observerspring
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.profiles.default=local
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
observer.security.admin.username=${OBSERVER_ADMIN_USERNAME:admin}
observer.security.admin.password=${OBSERVER_ADMIN_PASSWORD:change-me-please}
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:MGY2NTE2Y2JhNjBhMzg1ODc0NjNkYzRlM2I5NjExM2EzNTg5YTQ0NTQ3ZTBiNmY3M2M2NjA3YjExN2E4Nw==}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}
